/**
 * UX4G Indic Multilingual Support Engine
 * Supports 12 Scheduled Indian Languages + English
 */

export const INDIC_LANGUAGES = [
  { code: 'hi', name: 'हिन्दी', englishName: 'Hindi', script: 'Devanagari' },
  { code: 'en', name: 'English', englishName: 'English', script: 'Latin' },
  { code: 'bn', name: 'বাংলা', englishName: 'Bengali', script: 'Bengali' },
  { code: 'ta', name: 'தமிழ்', englishName: 'Tamil', script: 'Tamil' },
  { code: 'te', name: 'తెలుగు', englishName: 'Telugu', script: 'Telugu' },
  { code: 'mr', name: 'मराठी', englishName: 'Marathi', script: 'Devanagari' },
  { code: 'gu', name: 'ગુજરાતી', englishName: 'Gujarati', script: 'Gujarati' },
  { code: 'kn', name: 'ಕನ್ನಡ', englishName: 'Kannada', script: 'Kannada' },
  { code: 'ml', name: 'മലയാളം', englishName: 'Malayalam', script: 'Malayalam' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', englishName: 'Punjabi', script: 'Gurmukhi' },
  { code: 'or', name: 'ଓଡ଼ିଆ', englishName: 'Odia', script: 'Odia' },
  { code: 'as', name: 'অসমীয়া', englishName: 'Assamese', script: 'Bengali' }
];

export const UX4G_STRINGS = {
  hi: {
    govIndia: "भारत सरकार",
    skipContent: "मुख्य सामग्री पर जाएं",
    heroPill: "UX4G Design System v3.0 • SIH1454",
    heroTitlePrefix: "140 करोड़ नागरिकों की सुरक्षा के लिए समर्पित।",
    heroTitleAi: "AI द्वारा संचालित",
    heroSub: "फर्जी सरकारी वेबसाइटों, नकली योजनाओं और वित्तीय साइबर ठगी से बचने के लिए भारत का पहला संप्रभु साइबर रक्षा इंजन।",
    placeholder: "वेबसाइट का लिंक यहाँ पेस्ट करें (उदा: pmkisan.gov.in या g0v.in)...",
    verifyBtn: "सत्यापन करें",
    verifying: "जांच जारी है...",
    quickTry: "परीक्षण हेतु लिंक:",
    safeSite: "सुरक्षित (PM-Kisan)",
    fakeSite: "फर्जी क्लोन (g0v.in)",
    incomeTax: "आयकर पोर्टल (Authentic)",
    verdictSafe: "सत्यापित एवं प्रामाणिक",
    verdictThreat: "सावधान! फर्जी / नकली वेबसाइट",
    verdictCaution: "सतर्कता: संदिग्ध वेबसाइट",
    listenAudio: "आवाज़ में सुनें",
    stopAudio: "आवाज़ बंद करें",
    threatScoreLabel: "जोखिम स्कोर (Threat Score)",
    advisorySafe: "यह वेबसाइट पूरी तरह से प्रामाणिक और आधिकारिक सरकारी पोर्टल है। आप इस पर विश्वास के साथ कार्य कर सकते हैं।",
    advisoryThreat: "चेतावनी! यह वेबसाइट फर्जी है जो सरकारी पोर्टल की नकल कर रही है। अपना आधार नंबर, बैंक खाता, पैन या OTP यहाँ कभी दर्ज न करें!",
    advisoryCaution: "सावधानी बरतें। यह वेबसाइट आधिकारिक सरकारी रजिस्ट्री में दर्ज नहीं है। व्यक्तिगत विवरण दर्ज करने से पहले जांच करें।",
    layer1: "1. सरकारी डोमेन प्रमाणन (.gov.in / .nic.in)",
    layer2: "2. वर्तनी व नाम की नकल (Typosquatting)",
    layer3: "3. आधार व पासवर्ड चोरी फॉर्म (Credential Theft)",
    layer4: "4. एआई विजुअल क्लोनिंग (Lookalike Match)",
    layer5: "5. डोमेन पंजीकरण व उम्र (Domain Age)",
    card1Title: "महिला एवं बाल सुरक्षा",
    card1Desc: "ऑनलाइन उत्पीड़न, अवांछित संदेशों और साइबर अपराधों की गोपनीय रिपोर्ट दर्ज करें।",
    card2Title: "वित्तीय धोखाधड़ी रोकथाम",
    card2Desc: "नकली बैंक KYC, फर्जी सब्सिडी, लॉटरी व आधार OTP फ्रॉड से तुरंत सुरक्षा व सहायता।",
    card3Title: "CERT-In घटना डोजियर",
    card3Desc: "CERT-In और भारतीय साइबर अपराध समन्वय केंद्र (I4C) को कानूनी कार्रवाई हेतु डोजियर भेजें।",
    dossierBtn: "डोजियर डाउनलोड करें",
    helpline1930: "1930 पर कॉल करें",
    a11yTitle: "UX4G एक्सेसिबिलिटी विकल्प",
    colorAdjust: "रंग और कंट्रास्ट समायोजन",
    contentAdjust: "सामग्री समायोजन",
    assistiveTools: "सहायक उपकरण",
    monochrome: "मोनोक्रोम",
    highSaturate: "उच्च संतृप्ति",
    lowSaturate: "कम संतृप्ति",
    darkMode: "डार्क मोड",
    invertColors: "रंग उलटें",
    biggerText: "बड़ा पाठ (A+)",
    lineHeight: "पंक्ति ऊंचाई",
    textSpacing: "अक्षर दूरी",
    highlightLinks: "लिंक हाइलाइट",
    dyslexiaFont: "डिस्लेक्सिया अनुकूल",
    textMagnify: "पाठ आवर्धक",
    screenReader: "स्क्रीन रीडर",
    voiceSupport: "आवाज़ सहायता",
    hideImages: "चित्र छिपाएं",
    focusMode: "फोकस मोड",
    pauseAnimation: "एनिमेशन रोकें",
    resetAll: "सभी रीसेट करें",
    needHelp: "सहायता चाहिए?"
  },
  en: {
    govIndia: "Government of India",
    skipContent: "Skip to main content",
    heroPill: "UX4G Design System v3.0 • SIH1454",
    heroTitlePrefix: "Designed for billions of citizens.",
    heroTitleAi: "Powered by AI",
    heroSub: "A sovereign cyber protection ecosystem that enables citizens and agencies to detect fake government portals, phishing traps, and typosquatting scams.",
    placeholder: "Paste portal URL here (e.g., pmkisan.gov.in or g0v.in)...",
    verifyBtn: "Verify Portal",
    verifying: "Analyzing...",
    quickTry: "Quick Test Links:",
    safeSite: "Safe Portal (PM-Kisan)",
    fakeSite: "Fake Typosquat (g0v.in)",
    incomeTax: "IncomeTax (Authentic)",
    verdictSafe: "VERIFIED AUTHENTIC PORTAL",
    verdictThreat: "CRITICAL THREAT: FAKE CLONE",
    verdictCaution: "CAUTION: SUSPICIOUS DOMAIN",
    listenAudio: "Listen Audio",
    stopAudio: "Stop Audio",
    threatScoreLabel: "Threat Risk Score",
    advisorySafe: "This website is verified as an authentic Government of India portal. It is safe to use.",
    advisoryThreat: "DANGER! This website is a deceptive clone imitating government services. NEVER enter your Aadhaar, Bank Details, PAN, or OTP here!",
    advisoryCaution: "Exercise caution. This domain is not an official government portal. Verify authenticity before entering personal details.",
    layer1: "1. Sovereign TLD Authentication (.gov.in / .nic.in)",
    layer2: "2. Typosquatting & Spelling Traps Check",
    layer3: "3. Identity & Credential Theft Forms",
    layer4: "4. AI Visual Lookalike Detection",
    layer5: "5. Domain Age & Registry Verification",
    card1Title: "Women & Child Cyber Safety",
    card1Desc: "Confidential reporting for cyber harassment, impersonation, and fraudulent schemes.",
    card2Title: "Financial Cyber Fraud Defense",
    card2Desc: "Instant protection against fake KYC, stolen Aadhaar subsidy claims, and OTP traps.",
    card3Title: "CERT-In Incident Dossier",
    card3Desc: "Generate legal evidence dossiers for immediate takedown by NIXI, CERT-In, and I4C.",
    dossierBtn: "Download Dossier",
    helpline1930: "Call Helpline 1930",
    a11yTitle: "Accessibility Options by UX4G",
    colorAdjust: "Color & Contrast",
    contentAdjust: "Content Adjustment",
    assistiveTools: "Orientation & Assistive Tools",
    monochrome: "Monochrome",
    highSaturate: "High Saturate",
    lowSaturate: "Low Saturate",
    darkMode: "Dark Mode",
    invertColors: "Invert Colors",
    biggerText: "Bigger Text",
    lineHeight: "Line Height",
    textSpacing: "Text Spacing",
    highlightLinks: "Highlight Links",
    dyslexiaFont: "Dyslexia Friendly",
    textMagnify: "Text Magnify",
    screenReader: "Screen Reader",
    voiceSupport: "Voice Support",
    hideImages: "Hide Images",
    focusMode: "Focus Mode",
    pauseAnimation: "Pause Animation",
    resetAll: "Reset",
    needHelp: "Need Help?"
  }
};
