/**
 * UX4G Indic Multilingual Support Engine
 * Supports 12 Scheduled Indian Languages with Full Native UI & Audio Voice Synthesis
 */

export const INDIC_LANGUAGES = [
  { code: 'hi', name: 'हिन्दी', englishName: 'Hindi', bcp47: 'hi-IN' },
  { code: 'en', name: 'English', englishName: 'English', bcp47: 'en-IN' },
  { code: 'bn', name: 'বাংলা', englishName: 'Bengali', bcp47: 'bn-IN' },
  { code: 'ta', name: 'தமிழ்', englishName: 'Tamil', bcp47: 'ta-IN' },
  { code: 'te', name: 'తెలుగు', englishName: 'Telugu', bcp47: 'te-IN' },
  { code: 'mr', name: 'मराठी', englishName: 'Marathi', bcp47: 'mr-IN' },
  { code: 'gu', name: 'ગુજરાતી', englishName: 'Gujarati', bcp47: 'gu-IN' },
  { code: 'kn', name: 'ಕನ್ನಡ', englishName: 'Kannada', bcp47: 'kn-IN' },
  { code: 'ml', name: 'മലയാളം', englishName: 'Malayalam', bcp47: 'ml-IN' },
  { code: 'pa', name: 'ਪੰਜਾਬੀ', englishName: 'Punjabi', bcp47: 'pa-IN' },
  { code: 'or', name: 'ଓଡ଼ିଆ', englishName: 'Odia', bcp47: 'or-IN' },
  { code: 'as', name: 'অসমীয়া', englishName: 'Assamese', bcp47: 'as-IN' }
];

export const UX4G_STRINGS = {
  hi: {
    govIndia: "भारत सरकार",
    skipContent: "मुख्य सामग्री पर जाएं",
    brandSubtitle: "राष्ट्रीय मल्टी-सिग्नल AI फिशिंग व फर्जी पोर्टल पहचान प्रणाली",
    heroTitlePrefix: "किसी भी सरकारी वेबसाइट की तुरंत जांच करें।",
    heroTitleAi: "संप्रभु AI द्वारा सुरक्षित",
    heroSub: "आधार, पैन या बैंक विवरण दर्ज करने से पहले जांचें कि वेबसाइट असली (.gov.in) है या फर्जी साइबर क्लोन।",
    placeholder: "वेबसाइट का लिंक यहाँ पेस्ट करें (उदा: pmkisan.gov.in या g0v.in)...",
    verifyBtn: "सत्यापन करें",
    verifying: "जांच जारी है...",
    quickTry: "परीक्षण हेतु लिंक:",
    safeSite: "सुरक्षित (PM-Kisan)",
    fakeSite: "फर्जी क्लोन (g0v.in)",
    incomeTax: "आयकर पोर्टल (Authentic)",
    verdictSafe: "सत्यापित एवं प्रामाणिक",
    verdictThreat: "सावधान! फर्जी / नकली वेबसाइट",
    verdictCaution: "सतर्कता: संदिग्ध वेबसाइट",
    listenAudio: "आवाज़ में सुनें",
    stopAudio: "आवाज़ बंद करें",
    threatScoreLabel: "जोखिम स्कोर (Threat Score)",
    advisorySafe: "यह वेबसाइट पूरी तरह से प्रामाणिक और आधिकारिक सरकारी पोर्टल है। आप इस पर विश्वास के साथ कार्य कर सकते हैं।",
    advisoryThreat: "चेतावनी! यह वेबसाइट फर्जी है जो सरकारी पोर्टल की नकल कर रही है। अपना आधार नंबर, बैंक खाता, पैन या OTP यहाँ कभी दर्ज न करें!",
    advisoryCaution: "सावधानी बरतें। यह वेबसाइट आधिकारिक सरकारी रजिस्ट्री में दर्ज नहीं है। व्यक्तिगत विवरण दर्ज करने से पहले जांच करें।",
    layer1: "1. सरकारी डोमेन प्रमाणन (.gov.in / .nic.in)",
    layer2: "2. वर्तनी व नाम की नकल (Typosquatting)",
    layer3: "3. आधार व पासवर्ड चोरी फॉर्म (Credential Theft)",
    layer4: "4. एआई विजुअल क्लोनिंग (Lookalike Match)",
    layer5: "5. डोमेन पंजीकरण व उम्र (Domain Age)",
    sectionTitle: "नागरिक साइबर सुरक्षा सेवाएं",
    sectionSub: "फर्जी और संदिग्ध वेबसाइटों के खिलाफ तत्काल व वास्तविक समय सुरक्षा",
    card1Title: "महिला एवं बाल सुरक्षा",
    card1Desc: "ऑनलाइन उत्पीड़न, अवांछित संदेशों और साइबर अपराधों की गोपनीय रिपोर्ट दर्ज करें।",
    card1Btn: "सुरक्षित रिपोर्ट करें →",
    card2Title: "वित्तीय धोखाधड़ी रोकथाम",
    card2Desc: "नकली बैंक KYC, फर्जी सब्सिडी, लॉटरी व आधार OTP फ्रॉड से तुरंत सुरक्षा व सहायता।",
    card3Title: "अन्य साइबर अपराध",
    card3Desc: "रैंसमवेयर, पहचान चोरी, मैलवेयर, सोशल मीडिया हैकिंग व अन्य साइबर अपराधों की रिपोर्ट दर्ज करें।",
    card3Btn: "शिकायत दर्ज करें →",
    dossierBtn: "डोजियर डाउनलोड करें",
    helpline1930: "1930 पर कॉल करें",
    a11yTitle: "UX4G एक्सेसिबिलिटी विकल्प",
    colorAdjust: "रंग और कंट्रास्ट",
    contentAdjust: "सामग्री समायोजन",
    assistiveTools: "सहायक उपकरण",
    monochrome: "मोनोक्रोम",
    highSaturate: "उच्च संतृप्ति",
    lowSaturate: "कम संतृप्ति",
    darkMode: "डार्क मोड",
    invertColors: "रंग उलटें",
    biggerText: "बड़ा पाठ (A+)",
    lineHeight: "पंक्ति ऊंचाई",
    textSpacing: "अक्षर दूरी",
    highlightLinks: "लिंक हाइलाइट",
    dyslexiaFont: "डिस्लेक्सिया अनुकूल",
    textMagnify: "पाठ आवर्धक",
    screenReader: "स्क्रीन रीडर",
    voiceSupport: "आवाज़ सहायता",
    hideImages: "चित्र छिपाएं",
    focusMode: "फोकस मोड",
    pauseAnimation: "एनिमेशन रोकें",
    resetAll: "सभी रीसेट करें",
    needHelp: "सहायता चाहिए?",
    nationalPortalsHeading: "राष्ट्रीय पोर्टल",
    emergencyHelplinesHeading: "आपातकालीन हेल्पलाइन",
    footerAbout: "140 करोड़ भारतीय नागरिकों को फर्जी सरकारी पोर्टल और साइबर धोखाधड़ी से बचाने के लिए UX4G डिजाइन सिस्टम 3.0 के अनुरूप विकसित।",
    footerSIH: "UX4G डिजाइन सिस्टम 3.0 के अनुरूप • स्मार्ट इंडिया हैकाथॉन 2026 के अंतर्गत विकसित",
    closeModal: "बंद करें",
    copyDossier: "डोजियर कॉपी करें",
    copied: "कॉपी हो गया!",
    speechThreat: "सावधान! ... यह वेबसाइट पूरी तरह फर्जी है, और सरकारी पोर्टल की नकल कर रही है। ... कृपया अपना आधार नंबर, बैंक विवरण या ओटीपी कभी भी साझा न करें। ... तुरंत 1930 साइबर हेल्पलाइन पर कॉल करें।",
    speechSafe: "सत्यापित! ... यह भारत सरकार का प्रामाणिक और सुरक्षित आधिकारिक पोर्टल है। ... आप इस पर विश्वास के साथ कार्य कर सकते हैं।",
    speechCaution: "सतर्क रहें! ... यह वेबसाइट संदिग्ध है, और आधिकारिक सरकारी डोमेन से सत्यापित नहीं है।"
  },
  en: {
    govIndia: "Government of India",
    skipContent: "Skip to main content",
    brandSubtitle: "National Multi-Signal Phishing & Fake Portal Detection System",
    heroTitlePrefix: "Verify Any Government Portal Instantly.",
    heroTitleAi: "Protected by Sovereign AI",
    heroSub: "Check if a website, scheme, or subsidy portal is authentic (.gov.in) or a dangerous fake clone before entering Aadhaar, PAN, or OTP.",
    placeholder: "Paste portal URL here (e.g., pmkisan.gov.in or g0v.in)...",
    verifyBtn: "Verify Portal",
    verifying: "Analyzing...",
    quickTry: "Quick Test Links:",
    safeSite: "Safe Portal (PM-Kisan)",
    fakeSite: "Fake Typosquat (g0v.in)",
    incomeTax: "IncomeTax (Authentic)",
    verdictSafe: "VERIFIED AUTHENTIC PORTAL",
    verdictThreat: "CRITICAL THREAT: FAKE CLONE",
    verdictCaution: "CAUTION: SUSPICIOUS DOMAIN",
    listenAudio: "Listen Audio",
    stopAudio: "Stop Audio",
    threatScoreLabel: "Threat Risk Score",
    advisorySafe: "This website is verified as an authentic Government of India portal. It is safe to use.",
    advisoryThreat: "DANGER! This website is a deceptive clone imitating government services. NEVER enter your Aadhaar, Bank Details, PAN, or OTP here!",
    advisoryCaution: "Exercise caution. This domain is not an official government portal. Verify authenticity before entering personal details.",
    layer1: "1. Sovereign TLD Authentication (.gov.in / .nic.in)",
    layer2: "2. Typosquatting & Spelling Traps Check",
    layer3: "3. Identity & Credential Theft Forms",
    layer4: "4. AI Visual Lookalike Detection",
    layer5: "5. Domain Age & Registry Verification",
    sectionTitle: "Citizen Cyber Defense Services",
    sectionSub: "Instant safeguards and real-time defense against deceptive portals",
    card1Title: "Women & Child Cyber Safety",
    card1Desc: "Confidential reporting for cyber harassment, impersonation, and fraudulent schemes.",
    card1Btn: "Report Incident →",
    card2Title: "Financial Cyber Fraud Defense",
    card2Desc: "Instant protection against fake KYC, stolen Aadhaar subsidy claims, and OTP traps.",
    card3Title: "Other Cyber Crime",
    card3Desc: "Report ransomware, identity theft, malware, social media hacking, and other cyber crimes.",
    card3Btn: "Report Incident →",
    dossierBtn: "Download Dossier",
    helpline1930: "Call Helpline 1930",
    a11yTitle: "Accessibility Options by UX4G",
    colorAdjust: "Color & Contrast",
    contentAdjust: "Content Adjustment",
    assistiveTools: "Orientation & Assistive Tools",
    monochrome: "Monochrome",
    highSaturate: "High Saturate",
    lowSaturate: "Low Saturate",
    darkMode: "Dark Mode",
    invertColors: "Invert Colors",
    biggerText: "Bigger Text",
    lineHeight: "Line Height",
    textSpacing: "Text Spacing",
    highlightLinks: "Highlight Links",
    dyslexiaFont: "Dyslexia Friendly",
    textMagnify: "Text Magnify",
    screenReader: "Screen Reader",
    voiceSupport: "Voice Support",
    hideImages: "Hide Images",
    focusMode: "Focus Mode",
    pauseAnimation: "Pause Animation",
    resetAll: "Reset",
    needHelp: "Need Help?",
    nationalPortalsHeading: "National Portals",
    emergencyHelplinesHeading: "Emergency Helplines",
    footerAbout: "An AI/ML-driven sovereign cyber protection layer designed in alignment with the UX4G Design System 3.0 to protect 1.4 billion Indian citizens from deceptive phishing portals and typosquatting scams.",
    footerSIH: "Aligned with UX4G Design System 3.0 • Developed for Smart India Hackathon 2026",
    closeModal: "Close",
    copyDossier: "Copy Dossier",
    copied: "Copied!",
    speechThreat: "Critical Warning! ... This website is a deceptive clone imitating government services. ... Never enter your Aadhaar, bank details, or OTP here. ... Call Helpline 1930 immediately!",
    speechSafe: "Verified Authentic! ... This domain is an authenticated Government of India sovereign portal.",
    speechCaution: "Caution! ... This domain is unverified on the official government registry."
  },
  bn: {
    govIndia: "ভারত সরকার",
    skipContent: "মূল বিষয়বস্তুতে যান",
    brandSubtitle: "জাতীয় মাল্টি-সিগন্যাল সাইবার ও ভুয়ো পোর্টাল শনাক্তকরণ ব্যবস্থা",
    heroTitlePrefix: "যেকোনো সরকারি ওয়েবসাইট তাৎক্ষণিক যাচাই করুন।",
    heroTitleAi: "সার্বভৌম AI দ্বারা সুরক্ষিত",
    heroSub: "আধার, প্যান বা ব্যাংক তথ্য দেওয়ার আগে জেনে নিন পোর্টালটি আসল সরকারি ওয়েবসাইট নাকি ভুয়ো সাইবার ক্লোন।",
    placeholder: "ওয়েবসাইটের লিঙ্ক এখানে পেস্ট করুন...",
    verifyBtn: "যাচাই করুন",
    verifying: "বিশ্লেষণ চলছে...",
    quickTry: "পরীক্ষামূলক লিঙ্ক:",
    safeSite: "নিরাপদ (PM-Kisan)",
    fakeSite: "ভুয়ো ডোমেন (g0v.in)",
    incomeTax: "আয়কর পোর্টাল (প্রকৃত)",
    verdictSafe: "যাচাইকৃত ও আসল সরকারি পোর্টাল",
    verdictThreat: "বিপদ! ভুয়ো বা নকল ওয়েবসাইট",
    verdictCaution: "সতর্কতা: সন্দেহজনক লিঙ্ক",
    listenAudio: "ভয়েস শুনুন",
    stopAudio: "ভয়েস বন্ধ করুন",
    threatScoreLabel: "ঝুঁকি স্কোর (Threat Score)",
    advisorySafe: "এই ওয়েবসাইটটি ভারত সরকারের আসল পোর্টাল। এটি সম্পূর্ণ নিরাপদ।",
    advisoryThreat: "বিপদ! এটি সরকারি পোর্টালে নকল করা ভুয়ো সাইট। কখনোই আপনার আধার, ব্যাংক তথ্য বা ওটিপি দেবেন না!",
    advisoryCaution: "সতর্ক থাকুন। এই ডোমেনটি সরকারি তালিকায় যাচাই করা হয়নি।",
    layer1: "১. সরকারি ডোমেন প্রমাণীকরণ (.gov.in / .nic.in)",
    layer2: "২. বানান ও নামের প্রতারণা (Typosquatting)",
    layer3: "৩. তথ্য চুরি ফর্ম স্ক্যানার (Credential Theft)",
    layer4: "৪. AI ভিজ্যুয়াল ক্লোন শনাক্তকরণ",
    layer5: "৫. ডোমেন রেজিস্ট্রেশন ও বয়স বিশ্লেষণ",
    sectionTitle: "নাগরিক সাইবার সুরক্ষা পরিষেবা",
    sectionSub: "প্রতারণামূলক পোর্টালের বিরুদ্ধে তাৎক্ষণিক ও রিয়েল-টাইম সুরক্ষা",
    card1Title: "নারী ও শিশু সুরক্ষা",
    card1Desc: "অনলাইন হেনস্থা ও সাইবার অপরাধের গোপন অভিযোগ দায়ের করুন।",
    card1Btn: "অভিযোগ দায়ের করুন →",
    card2Title: "আর্থিক জালিয়াতি প্রতিরোধ",
    card2Desc: "ভুয়ো কেওয়াইসি, আধার ওটিপি জালিয়াতি থেকে ২৪x৭ সহায়তা ও সুরক্ষা।",
    card3Title: "অন্যান্য সাইবার অপরাধ",
    card3Desc: "র‌্যানসমওয়্যার, পরিচয় চুরি, ম্যালওয়্যার ও অন্যান্য সাইবার অপরাধের অভিযোগ দায়ের করুন।",
    card3Btn: "অভিযোগ দায়ের করুন →",
    dossierBtn: "ডসিয়ার ডাউনলোড করুন",
    helpline1930: "১৯৩০ হেল্পলাইনে কল করুন",
    a11yTitle: "UX4G অ্যাক্সেসিবিলিটি বিকল্প",
    colorAdjust: "রং ও বৈসাদৃশ্য",
    contentAdjust: "বিষয়বস্তু সমন্বয়",
    assistiveTools: "সহায়ক সরঞ্জাম",
    monochrome: "মনোক্রোম",
    highSaturate: "উচ্চ স্যাচুরেশন",
    lowSaturate: "কম স্যাচুরেশন",
    darkMode: "ডার্ক মোড",
    invertColors: "রং উল্টান",
    biggerText: "বড় লেখা (A+)",
    lineHeight: "লাইনের উচ্চতা",
    textSpacing: "শব্দের ব্যবধান",
    highlightLinks: "লিঙ্ক হাইলাইট",
    dyslexiaFont: "ডিসলেক্সিয়া ফন্ট",
    textMagnify: "টেক্সট ম্যাগনিফায়ার",
    screenReader: "স্ক্রিন রিডার",
    voiceSupport: "ভয়েস সাপোর্ট",
    hideImages: "ছবি লুকান",
    focusMode: "ফোকাস মোড",
    pauseAnimation: "অ্যানিমেশন থামান",
    resetAll: "রিসেট করুন",
    needHelp: "সাহায্য প্রয়োজন?",
    nationalPortalsHeading: "জাতীয় পোর্টাল",
    emergencyHelplinesHeading: "জরুরি হেল্পলাইন",
    footerAbout: "১৪০ কোটি ভারতীয় নাগরিককে ভুয়ো সরকারি পোর্টাল এবং সাইবার জালিয়াতি থেকে রক্ষা করতে UX4G ডিজাইন সিস্টেম ৩.০ অনুসারে তৈরি।",
    footerSIH: "UX4G ডিজাইন সিস্টেম ৩.০ অনুসারে • স্মার্ট ইন্ডিয়া হ্যাকাথন ২০২৬",
    closeModal: "বন্ধ করুন",
    copyDossier: "ডসিয়ার কপি করুন",
    copied: "কপি হয়েছে!",
    speechThreat: "সাবধান! ... এটি একটি সম্পূর্ণ ভুয়ো ও প্রতারণামূলক ওয়েবসাইট। ... কখনোই আপনার আধার, ব্যাংক একাউন্ট বা ওটিপি দেবেন না। ... অবিলম্বে ১৯৩০ নম্বরে কল করুন।",
    speechSafe: "যাচাইকৃত! ... এটি ভারত সরকারের একটি আসল ও সম্পূর্ণ নিরাপদ পোর্টাল।",
    speechCaution: "সতর্ক থাকুন! ... এই ডোমেনটি সরকারি তালিকায় যাচাই করা হয়নি।"
  },
  ta: {
    govIndia: "இந்திய அரசு",
    skipContent: "முதன்மை உள்ளடக்கத்திற்குச் செல்க",
    brandSubtitle: "தேசிய பல-சமிக்ஞை போலி போர்டல் கண்டறிதல் அமைப்பு",
    heroTitlePrefix: "எந்தவொரு அரசு வலைத்தளத்தையும் உடனடியாக சரிபார்க்கவும்.",
    heroTitleAi: "தேசிய AI மூலம் பாதுகாக்கப்பட்டது",
    heroSub: "ஆதார், பான் அல்லது வங்கி விவரங்களை உள்ளிடுவதற்கு முன், அது உண்மையான அரசு வலைத்தளமா அல்லது போலி தளமா என கண்டறியவும்.",
    placeholder: "வலைத்தள இணைப்பை இங்கே உள்ளிடவும்...",
    verifyBtn: "சரிபார்க்கவும்",
    verifying: "ஆராய்கிறது...",
    quickTry: "சோதனை இணைப்புகள்:",
    safeSite: "பாதுகாப்பானது (PM-Kisan)",
    fakeSite: "போலி தளம் (g0v.in)",
    incomeTax: "வருமான வரி (உண்மையானது)",
    verdictSafe: "உண்மையான அரசு போர்டல்",
    verdictThreat: "எச்சரிக்கை! போலி வலைத்தளம்",
    verdictCaution: "எச்சரிக்கை: சந்தேகத்திற்குரிய தளம்",
    listenAudio: "குரலில் கேட்கவும்",
    stopAudio: "குரலை நிறுத்தவும்",
    threatScoreLabel: "அபாய மதிப்பீடு (Threat Score)",
    advisorySafe: "இந்த வலைத்தளம் இந்திய அரசால் சரிபார்க்கப்பட்டது. பாதுகாப்பாக பயன்படுத்தலாம்.",
    advisoryThreat: "ஆபத்து! இது அரசு தளத்தை நகலெடுக்கும் போலி வலைத்தளம். உங்கள் ஆதார், வங்கி விவரங்கள் அல்லது OTP-ஐ ஒருபோதும் உள்ளிட வேண்டாம்!",
    advisoryCaution: "கவனமாக இருங்கள். இந்த தளம் அதிகாரப்பூர்வ அரசு பதிவேட்டில் சரிபார்க்கப்படவில்லை.",
    layer1: "1. அதிகாரப்பூர்வ அரசு டொமைன் (.gov.in / .nic.in)",
    layer2: "2. எழுத்துப் பிழை ஏமாற்று சரிபார்ப்பு (Typosquatting)",
    layer3: "3. தரவு திருட்டு படிவ சோதனை (Credential Theft)",
    layer4: "4. AI காட்சி நகல் கண்டறிதல்",
    layer5: "5. டொமைன் பதிவு காலம் மற்றும் நம்பகத்தன்மை",
    sectionTitle: "குடிமக்கள் சைபர் பாதுகாப்பு சேவைகள்",
    sectionSub: "ஏமாற்று வலைத்தளங்களுக்கு எதிரான உடனடி நிகழ்நேர பாதுகாப்பு",
    card1Title: "பெண்கள் மற்றும் குழந்தைகள் பாதுகாப்பு",
    card1Desc: "இணைய தொல்லைகள் மற்றும் சைபர் குற்றங்கள் குறித்த ரகசிய புகார் பதிவு.",
    card1Btn: "புகார் செய்க →",
    card2Title: "நிதி மோசடி தடுப்பு",
    card2Desc: "போலி கேஒய்சி, வங்கி மோசடிகளில் இருந்து 24x7 உடனடி பாதுகாப்பு.",
    card3Title: "பிற சைபர் குற்றங்கள்",
    card3Desc: "ரான்சம்வேர், அடையாள திருட்டு, மால்வேர் மற்றும் பிற சைபர் குற்றங்களை புகாரளிக்கவும்.",
    card3Btn: "புகார் செய்க →",
    dossierBtn: "ஆவணத்தை பதிவிறக்கவும்",
    helpline1930: "1930 உதவி எண்",
    a11yTitle: "UX4G அணுகல்தன்மை விருப்பங்கள்",
    colorAdjust: "வண்ணம் மற்றும் மாறுபாடு",
    contentAdjust: "உள்ளடக்க மாற்றம்",
    assistiveTools: "உதவி கருவிகள்",
    monochrome: "மோனோக்ரோம்",
    highSaturate: "அதிக செறிவு",
    lowSaturate: "குறைந்த செறிவு",
    darkMode: "டார்க் பயன்முறை",
    invertColors: "வண்ணங்களை மாற்றவும்",
    biggerText: "பெரிய உரை (A+)",
    lineHeight: "வரி இடைவெளி",
    textSpacing: "சொல் இடைவெளி",
    highlightLinks: "இணைப்புகளை முன்னிலைப்படுத்து",
    dyslexiaFont: "டிஸ்லெக்ஸியா எழுத்துரு",
    textMagnify: "உரை உருப்பெருக்கி",
    screenReader: "திரை வாசிப்பான்",
    voiceSupport: "குரல் உதவி",
    hideImages: "படங்களை மறை",
    focusMode: "கவன பயன்முறை",
    pauseAnimation: "அசைவூட்டத்தை நிறுத்து",
    resetAll: "மீட்டமைக்கவும்",
    needHelp: "உதவி தேவையா?",
    nationalPortalsHeading: "தேசிய போர்டல்கள்",
    emergencyHelplinesHeading: "அவசர உதவி எண்கள்",
    footerAbout: "140 கோடி இந்திய குடிமக்களை போலி போர்டல்கள் மற்றும் இணைய மோசடிகளிலிருந்து பாதுகாக்க UX4G அமைப்பு 3.0 அடிப்படையில் உருவாக்கப்பட்டது.",
    footerSIH: "UX4G வடிவமைப்பு அமைப்பு 3.0 • ஸ்மார்ட் இந்தியா ஹேக்கத்தான் 2026",
    closeModal: "மூடுக",
    copyDossier: "ஆவணத்தை நகலெடு",
    copied: "நகலெடுக்கப்பட்டது!",
    speechThreat: "எச்சரிக்கை! ... இது முற்றிலும் போலியான ஏமாற்று வலைத்தளம். ... உங்கள் ஆதார் எண், வங்கி கணக்கு அல்லது ஓடிபியை பகிர வேண்டாம். ... உடனடியாக 1930 எண்ணை அழைக்கவும்.",
    speechSafe: "சரிபார்க்கப்பட்டது! ... இது உண்மையான இந்திய அரசு வலைத்தளமாகும்.",
    speechCaution: "கவனமாக இருங்கள்! ... இந்த தளம் அரசு பட்டியலில் சரிபார்க்கப்படவில்லை."
  },
  te: {
    govIndia: "భారత ప్రభుత్వం",
    skipContent: "ప్రధాన విషయానికి వెళ్లండి",
    brandSubtitle: "జాతీయ మల్టీ-సిగ్నల్ నకిలీ పోర్టల్ గుర్తింపు వ్యవస్థ",
    heroTitlePrefix: "ఏదైనా ప్రభుత్వ వెబ్‌సైట్‌ను తక్షణమే ధృవీకరించండి.",
    heroTitleAi: "సార్వభౌమ AI రక్షణతో",
    heroSub: "ఆధార్, పాన్ లేదా బ్యాంక్ వివరాలను నమోదు చేయడానికి ముందు, అది అసలైన ప్రభుత్వ పోర్టలా లేదా నకిలీ క్లోనా అని తనిఖీ చేయండి.",
    placeholder: "వెబ్‌సైట్ లింక్‌ను ఇక్కడ పేస్ట్ చేయండి...",
    verifyBtn: "ధృవీకరించండి",
    verifying: "పరిశీలిస్తోంది...",
    quickTry: "పరీక్ష లింకులు:",
    safeSite: "సురక్షితమైనది (PM-Kisan)",
    fakeSite: "నకిలీ క్లోన్ (g0v.in)",
    incomeTax: "ఆదాయపు పన్ను పోర్టల్",
    verdictSafe: "ధృవీకరించబడిన అసలైన పోర్టల్",
    verdictThreat: "ప్రమాదం! నకిలీ వెబ్‌సైట్",
    verdictCaution: "హెచ్చరిక: అనుమానాస్పద లింక్",
    listenAudio: "వాయిస్ వినండి",
    stopAudio: "వాయిస్ ఆపండి",
    threatScoreLabel: "ప్రమాద స్కోర్ (Threat Score)",
    advisorySafe: "ఈ వెబ్‌సైట్ భారత ప్రభుత్వం ద్వారా ధృవీకరించబడినది. ఇది సురక్షితం.",
    advisoryThreat: "హెచ్చరిక! ఇది నకిలీ వెబ్‌సైట్. మీ ఆధార్, బ్యాంక్ వివరాలు లేదా OTPని ఎప్పుడూ నమోదు చేయవద్దు!",
    advisoryCaution: "జాగ్రత్తగా ఉండండి. ఈ డొమైన్ అధికారిక ప్రభుత్వ రిజిస్ట్రీలో ధృవీకరించబడలేదు.",
    layer1: "1. అధికారిక ప్రభుత్వ డొమైన్ (.gov.in / .nic.in)",
    layer2: "2. అక్షరాల మోసం తనిఖీ (Typosquatting)",
    layer3: "3. డేటా దొంగతనం ఫారాల గుర్తింపు",
    layer4: "4. AI విజువల్ క్లోన్ గుర్తింపు",
    layer5: "5. డొమైన్ రిజిస్ట్రేషన్ మరియు వయస్సు",
    sectionTitle: "పౌర సైబర్ రక్షణ సేవలు",
    sectionSub: "మోసపూరిత పోర్టల్‌ల నుండి తక్షణ నిజ-సమయ రక్షణ",
    card1Title: "మహిళలు మరియు పిల్లల రక్షణ",
    card1Desc: "సైబర్ వేధింపులపై గోప్యంగా ఫిర్యాదు చేయండి.",
    card1Btn: "ఫిర్యాదు చేయండి →",
    card2Title: "ఆర్థిక మోసాల నివారణ",
    card2Desc: "నకిలీ KYC మరియు OTP మోసాల నుండి 24x7 తక్షణ రక్షణ.",
    card3Title: "ఇతర సైబర్ నేరాలు",
    card3Desc: "రాన్సమ్‌వేర్, గుర్తింపు దొంగతనం, మాల్వేర్ మరియు ఇతర సైబర్ నేరాలను నివేదించండి.",
    card3Btn: "ఫిర్యాదు చేయండి →",
    dossierBtn: "నివేదిక డౌన్‌లోడ్",
    helpline1930: "1930 కి కాల్ చేయండి",
    a11yTitle: "UX4G ప్రాప్యత ఎంపికలు",
    colorAdjust: "రంగు మరియు కాంట్రాస్ట్",
    contentAdjust: "కంటెంట్ సర్దుబాటు",
    assistiveTools: "సహాయక సాధనాలు",
    monochrome: "మోనోక్రోమ్",
    highSaturate: "అధిక సంతృప్తత",
    lowSaturate: "తక్కువ సంతృప్తత",
    darkMode: "డార్క్ మోడ్",
    invertColors: "రంగులను తిప్పండి",
    biggerText: "పెద్ద వచనం (A+)",
    lineHeight: "లైన్ ఎత్తు",
    textSpacing: "పదాల అంతరం",
    highlightLinks: "లింకులను హైలైట్ చేయండి",
    dyslexiaFont: "డిస్లెక్సియా ఫాంట్",
    textMagnify: "టెక్స్ట్ మాగ్నిఫైయర్",
    screenReader: "స్క్రీన్ రీడర్",
    voiceSupport: "వాయిస్ మద్దతు",
    hideImages: "చిత్రాలను దాచు",
    focusMode: "ఫోకస్ మోడ్",
    pauseAnimation: "యానిమేషన్ ఆపండి",
    resetAll: "రీసెట్ చేయండి",
    needHelp: "సహాయం కావాలా?",
    nationalPortalsHeading: "జాతీయ పోర్టల్‌లు",
    emergencyHelplinesHeading: "అత్యవసర హెల్ప్‌లైన్లు",
    footerAbout: "140 కోట్ల మంది భారతీయ పౌరులను నకిలీ పోర్టల్‌లు మరియు సైబర్ మోసాల నుండి రక్షించడానికి UX4G డిజైన్ సిస్టమ్ 3.0 ఆధారంగా అభివృద్ధి చేయబడింది.",
    footerSIH: "UX4G డిజైన్ సిస్టమ్ 3.0 • స్మార్ట్ ఇండియా హ్యాకథాన్ 2026",
    closeModal: "మూసివేయి",
    copyDossier: "నివేదికను కాపీ చేయండి",
    copied: "కాపీ అయింది!",
    speechThreat: "హెచ్చరిక! ... ఇది పూర్తిగా నకిలీ వెబ్‌సైట్. ... మీ ఆధార్ లేదా బ్యాంక్ వివరాలను ఎప్పుడూ ఇవ్వవద్దు. ... వెంటనే 1930 నంబర్‌కు కాల్ చేయండి.",
    speechSafe: "ధృవీకరించబడింది! ... ఇది అసలైన భారత ప్రభుత్వ పోర్టల్.",
    speechCaution: "జాగ్రత్తగా ఉండండి! ... ఈ డొమైన్ ప్రభుత్వ జాబితాలో లేదు."
  },
  mr: {
    govIndia: "भारत सरकार",
    skipContent: "मुख्य सामग्रीकडे जा",
    brandSubtitle: "राष्ट्रीय मल्टी-सिग्नल बनावट पोर्टल शोध प्रणाली",
    heroTitlePrefix: "कोणत्याही सरकारी संकेतस्थळाची त्वरित पडताळणी करा.",
    heroTitleAi: "संप्रभु AI द्वारे सुरक्षित",
    heroSub: "आधार, पॅन किंवा बँक माहिती भरण्यापूर्वी तपासा की पोर्टल अधिकृत सरकारी संकेतस्थळ आहे की बनावट सायबर क्लोन.",
    placeholder: "संकेतस्थळाची लिंक येथे टाका...",
    verifyBtn: "पडताळणी करा",
    verifying: "तपासणी सुरू आहे...",
    quickTry: "नमुना लिंक्स:",
    safeSite: "सुरक्षित (PM-Kisan)",
    fakeSite: "बनावट क्लोन (g0v.in)",
    incomeTax: "आयकर पोर्टल (अस्सल)",
    verdictSafe: "प्रमाणित व अस्सल सरकारी पोर्टल",
    verdictThreat: "सावधान! बनावट / बनावट वेबसाइट",
    verdictCaution: "सतर्कता: संशयास्पद वेबसाइट",
    listenAudio: "आवाजात ऐका",
    stopAudio: "आवाज बंद करा",
    threatScoreLabel: "धोका गुण (Threat Score)",
    advisorySafe: "ही वेबसाइट भारत सरकारचे अस्सल पोर्टल आहे. वापरण्यास सुरक्षित आहे.",
    advisoryThreat: "धोका! ही सरकारी पोर्टलची नक्कल करणारी बनावट वेबसाइट आहे. आधार, बँक माहिती किंवा OTP कधीही देऊ नका!",
    advisoryCaution: "काळजी घ्या. हे डोमेन अधिकृत सरकारी नोंदणीत प्रमाणित नाही.",
    layer1: "१. अधिकृत सरकारी डोमेन (.gov.in / .nic.in)",
    layer2: "२. चुकीच्या स्पेलिंगची फसवणूक (Typosquatting)",
    layer3: "३. माहिती चोरी फॉर्म शोधक (Credential Theft)",
    layer4: "४. AI व्हिज्युअल क्लोन ओळख",
    layer5: "५. डोमेन नोंदणी आणि वय तपासणी",
    sectionTitle: "नागरिक सायबर सुरक्षा सेवा",
    sectionSub: "फसव्या संकेतस्थळांविरुद्ध त्वरित व रिअल-टाइम संरक्षण",
    card1Title: "महिला व बाल सुरक्षा",
    card1Desc: "ऑनलाइन छळ आणि सायबर गुन्ह्यांची गोपनीय तक्रार नोंदवा.",
    card1Btn: "तक्रार नोंदवा →",
    card2Title: "आर्थिक फसवणूक प्रतिबंध",
    card2Desc: "बनावट केवायसी आणि ओटीपी फ्रॉडपासून २४x७ त्वरित मदत.",
    card3Title: "इतर सायबर गुन्हे",
    card3Desc: "रॅन्समवेअर, ओळख चोरी, मालवेअर व इतर सायबर गुन्ह्यांची तक्रार नोंदवा.",
    card3Btn: "तक्रार नोंदवा →",
    dossierBtn: "डोजियर डाउनलोड करा",
    helpline1930: "१९३० वर कॉल करा",
    a11yTitle: "UX4G प्रवेशयोग्यता पर्याय",
    colorAdjust: "रंग आणि कॉन्ट्रास्ट",
    contentAdjust: "सामग्री समायोजन",
    assistiveTools: "सहाय्यक साधने",
    monochrome: "मोनोक्रोम",
    highSaturate: "उच्च संपृक्तता",
    lowSaturate: "कमी संपृक्तता",
    darkMode: "डार्क मोड",
    invertColors: "रंग उलटा",
    biggerText: "मोठा मजकूर (A+)",
    lineHeight: "ओळ उंची",
    textSpacing: "अक्षर अंतर",
    highlightLinks: "लिंक्स हायलाइट करा",
    dyslexiaFont: "डिस्लेक्सिया अनुकूल",
    textMagnify: "मजकूर भिंग",
    screenReader: "स्क्रीन रीडर",
    voiceSupport: "आवाज समर्थन",
    hideImages: "चित्रे लपवा",
    focusMode: "फोकस मोड",
    pauseAnimation: "अ‍ॅनिमेशन थांबवा",
    resetAll: "रीसेट करा",
    needHelp: "मदत हवी आहे?",
    nationalPortalsHeading: "राष्ट्रीय पोर्टल्स",
    emergencyHelplinesHeading: "आपत्कालीन हेल्पलाइन",
    footerAbout: "१४० कोटी भारतीय नागरिकांना बनावट पोर्टल आणि सायबर फसवणुकीपासून वाचवण्यासाठी UX4G डिझाइन सिस्टम ३.० नुसार विकसित.",
    footerSIH: "UX4G डिझाइन सिस्टम ३.० • स्मार्ट इंडिया हॅकाथॉन २०२६",
    closeModal: "बंद करा",
    copyDossier: "डोजियर कॉपी करा",
    copied: "कॉपी झाले!",
    speechThreat: "सावधान! ... ही संपूर्णपणे बनावट वेबसाइट आहे. ... तुमचा आधार नंबर किंवा बँक माहिती कधीही शेअर करू नका. ... त्वरित १९३० सायबर हेल्पलाइनवर कॉल करा.",
    speechSafe: "प्रमाणित! ... हे भारत सरकारचे अधिकृत व सुरक्षित पोर्टल आहे.",
    speechCaution: "सतर्क राहा! ... हे डोमेन सरकारी नोंदणीत नाही."
  },
  gu: {
    govIndia: "ભારત સરકાર",
    skipContent: "મુખ્ય વિષયવસ્તુ પર જાઓ",
    brandSubtitle: "રાષ્ટ્રીય મલ્ટી-સિગ્નલ નકલી પોર્ટલ તપાસ પ્રણાલી",
    heroTitlePrefix: "કોઈપણ સરકારી વેબસાઇટની તાત્કાલિક ચકાસણી કરો.",
    heroTitleAi: "સાર્વભૌમ AI દ્વારા સુરક્ષિત",
    heroSub: "આધાર, પાન અથવા બેંક વિગતો દાખલ કરતા પહેલા ચકાસો કે પોર્ટલ અસલ સરકારી વેબસાઇટ છે કે નકલી સાયબર ક્લોન.",
    placeholder: "વેબસાઇટની લિંક અહીં પેસ્ટ કરો...",
    verifyBtn: "ચકાસો",
    verifying: "તપાસ ચાલુ છે...",
    quickTry: "ચકાસણી લિંક્સ:",
    safeSite: "સુરક્ષિત (PM-Kisan)",
    fakeSite: "નકલી સાઇટ (g0v.in)",
    incomeTax: "ઇન્કમ ટેક્સ પોર્ટલ",
    verdictSafe: "પ્રમાણિત સરકારી પોર્ટલ",
    verdictThreat: "ચેતવણી! નકલી વેબસાઇટ",
    verdictCaution: "સાવધાની: શંકાસ્પદ લિંક",
    listenAudio: "અવાજમાં સાંભળો",
    stopAudio: "અવાજ બંધ કરો",
    threatScoreLabel: "જોખમ સ્કોર (Threat Score)",
    advisorySafe: "આ વેબસાઇટ ભારત સરકારનું અસલ પોર્ટલ છે. સંપૂર્ણ સુરક્ષિત છે.",
    advisoryThreat: "જોખમ! આ નકલી વેબસાઇટ છે. આધાર, બેંક વિગતો કે OTP ક્યારેય દાખલ કરશો નહીં!",
    advisoryCaution: "સાવચેત રહો. આ ડોમેન સરકારી રજિસ્ટ્રીમાં પ્રમાણિત નથી.",
    layer1: "1. અધિકૃત સરકારી ડોમેન (.gov.in / .nic.in)",
    layer2: "2. સ્પેલિંગ છેતરપિંડી ચકાસણી (Typosquatting)",
    layer3: "3. માહિતી ચોરી ફોર્મ સ્કેનર",
    layer4: "4. AI વિઝ્યુઅલ ક્લોન ઓળખ",
    layer5: "5. ડોમેન રજિસ્ટ્રેશન અને ઉંમર",
    sectionTitle: "નાગરિક સાયબર સુરક્ષા સેવાઓ",
    sectionSub: "છેતરપિંડીવાળા પોર્ટલ સામે તાત્કાલિક રીઅલ-ટાઇમ રક્ષણ",
    card1Title: "મહિલા અને બાળ સુરક્ષા",
    card1Desc: "ઓનલાઇન સતામણી અને સાયબર ગુનાઓની ગુપ્ત ફરિયાદ નોંધાવો.",
    card1Btn: "ફરિયાદ નોંધાવો →",
    card2Title: "નાણાકીય છેતરપિંડી નિવારણ",
    card2Desc: "નકલી KYC અને ઓટીપી ફ્રોડ સામે 24x7 તાત્કાલિક સહાય.",
    card3Title: "અન્ય સાયબર ગુનાઓ",
    card3Desc: "રેન્સમવેર, ઓળખ ચોરી, માલવેર અને અન્ય સાયબર ગુનાઓની ફરિયાદ નોંધાવો.",
    card3Btn: "ફરિયાદ નોંધાવો →",
    dossierBtn: "અહેવાલ ડાઉનલોડ કરો",
    helpline1930: "1930 પર કૉલ કરો",
    a11yTitle: "UX4G એક્સેસિબિલિટી વિકલ્પો",
    colorAdjust: "રંગ અને કોન્ટ્રાસ્ટ",
    contentAdjust: "સામગ્રી સેટિંગ્સ",
    assistiveTools: "સહાયક સાધનો",
    monochrome: "મોનોક્રોમ",
    highSaturate: "ઉચ્ચ સંતૃપ્તિ",
    lowSaturate: "ઓછી સંતૃપ્તિ",
    darkMode: "ડાર્ક મોડ",
    invertColors: "રંગો ઉલટાવો",
    biggerText: "મોટો લખાણ (A+)",
    lineHeight: "લાઇન ઊંચાઈ",
    textSpacing: "શબ્દ અંતર",
    highlightLinks: "લિંક્સ હાઇલાઇટ કરો",
    dyslexiaFont: "ડિસ્લેક્સિયા ફોન્ટ",
    textMagnify: "ટેક્સ્ટ મેગ્નિફાયર",
    screenReader: "સ્ક્રીન રીડર",
    voiceSupport: "વોઇસ સપોર્ટ",
    hideImages: "ચિત્રો છુપાવો",
    focusMode: "ફોકસ મોડ",
    pauseAnimation: "એનિમેશન થોભાવો",
    resetAll: "રીસેટ કરો",
    needHelp: "મદદ જોઈએ છે?",
    nationalPortalsHeading: "રાષ્ટ્રીય પોર્ટલ",
    emergencyHelplinesHeading: "ઇમરજન્સી હેલ્પલાઇન",
    footerAbout: "૧૪૦ કરોડ નાગરિકોને સાયબર છેતરપિંડીથી બચાવવા માટે UX4G ડિઝાઇન સિસ્ટમ 3.0 ના આધારે વિકસાવવામાં આવી છે.",
    footerSIH: "UX4G ડિઝાઇન સિસ્ટમ 3.0 • સ્માર્ટ ઇન્ડિયા હેકાથોન 2026",
    closeModal: "બંધ કરો",
    copyDossier: "અહેવાલ કોપી કરો",
    copied: "કોપી થઈ ગયું!",
    speechThreat: "સાવધાન! ... આ સંપૂર્ણ નકલી વેબસાઇટ છે. ... આધાર અથવા બેંક વિગતો ક્યારેય શેર કરશો નહીં. ... તરત 1930 હેલ્પલાઇન પર કૉલ કરો.",
    speechSafe: "ચકાસાયેલ! ... આ ભારત સરકારનું પ્રમાણિત પોર્ટલ છે.",
    speechCaution: "સાવચેત રહો! ... આ સાઇટ સરકારી યાદીમાં નથી."
  },
  kn: {
    govIndia: "ಭಾರತ ಸರ್ಕಾರ",
    skipContent: "ಮುಖ್ಯ ವಿಷಯಕ್ಕೆ ಹೋಗಿ",
    brandSubtitle: "ರಾಷ್ಟ್ರೀಯ ಮಲ್ಟಿ-ಸಿಗ್ನಲ್ ನಕಲಿ ಪೋರ್ಟಲ್ ಪತ್ತೆ ವ್ಯವಸ್ಥೆ",
    heroTitlePrefix: "ಯಾವುದೇ ಸರ್ಕಾರಿ ವೆಬ್‌ಸೈಟ್ ಅನ್ನು ತಕ್ಷಣ ಪರಿಶೀಲಿಸಿ.",
    heroTitleAi: "ಸಾರ್ವಭೌಮ AI ಮೂಲಕ ಸುರಕ್ಷಿತ",
    heroSub: "ಆಧಾರ್, ಪ್ಯಾನ್ ಅಥವಾ ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ನಮೂದಿಸುವ ಮೊದಲು, ಪೋರ್ಟಲ್ ನಿಜವಾದ ಸರ್ಕಾರಿ ತಾಣವೇ ಅಥವಾ ನಕಲಿ ಕ್ಲೋನ್ ಎಂಬುದನ್ನು ಪರಿಶೀಲಿಸಿ.",
    placeholder: "ವೆಬ್‌ಸೈಟ್ ಲಿಂಕ್ ಅನ್ನು ಇಲ್ಲಿ ನಮೂದಿಸಿ...",
    verifyBtn: "ಪರಿಶೀಲಿಸಿ",
    verifying: "ವಿಶ್ಲೇಷಿಸಲಾಗುತ್ತಿದೆ...",
    quickTry: "ಪರೀಕ್ಷಾ ಲಿಂಕ್‌ಗಳು:",
    safeSite: "ಸುರಕ್ಷಿತ (PM-Kisan)",
    fakeSite: "ನಕಲಿ ತಾಣ (g0v.in)",
    incomeTax: "ಆದಾಯ ತೆರಿಗೆ ಪೋರ್ಟಲ್",
    verdictSafe: "ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಪೋರ್ಟಲ್",
    verdictThreat: "ಎಚ್ಚರಿಕೆ! ನಕಲಿ ವೆಬ್‌ಸೈಟ್",
    verdictCaution: "ಎಚ್ಚರಿಕೆ: ಶಂಕಾಸ್ಪದ ಲಿಂಕ್",
    listenAudio: "ಧ್ವನಿಯಲ್ಲಿ ಕೇಳಿ",
    stopAudio: "ಧ್ವನಿ ನಿಲ್ಲಿಸಿ",
    threatScoreLabel: "ಅಪಾಯದ ಸ್ಕೋರ್ (Threat Score)",
    advisorySafe: "ಈ ವೆಬ್‌ಸೈಟ್ ಭಾರತ ಸರ್ಕಾರದ ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ಆಗಿದೆ. ಇದು ಸುರಕ್ಷಿತವಾಗಿದೆ.",
    advisoryThreat: "ಅಪಾಯ! ಇದು ನಕಲಿ ವೆಬ್‌ಸೈಟ್ ಆಗಿದೆ. ನಿಮ್ಮ ಆಧಾರ್, ಬ್ಯಾಂಕ್ ವಿವರಗಳು ಅಥವಾ OTP ಅನ್ನು ಎಂದಿಗೂ ನಮೂದಿಸಬೇಡಿ!",
    advisoryCaution: "ಎಚ್ಚರದಿಂದಿರಿ. ಈ ಡೊಮೇನ್ ಸರ್ಕಾರಿ ನೋಂದಣಿಯಲ್ಲಿ ಪರಿಶೀಲಿಸಲ್ಪಟ್ಟಿಲ್ಲ.",
    layer1: "1. ಅಧಿಕೃತ ಸರ್ಕಾರಿ ಡೊಮೇನ್ (.gov.in / .nic.in)",
    layer2: "2. ಸ್ಪೆಲ್ಲಿಂಗ್ ಮೋಸ ತಪಾಸಣೆ (Typosquatting)",
    layer3: "3. ಮಾಹಿತಿ ಕಳ್ಳತನ ಫಾರ್ಮ್‌ಗಳ ಪತ್ತೆ",
    layer4: "4. AI ದೃಶ್ಯ ನಕಲು ಗುರುತಿಸುವಿಕೆ",
    layer5: "5. ಡೊಮೇನ್ ನೋಂದಣಿ ಮತ್ತು ವಯಸ್ಸು",
    sectionTitle: "ನಾಗರಿಕ ಸೈಬರ್ ಭದ್ರತಾ ಸೇವೆಗಳು",
    sectionSub: "ಮೋಸದ ಪೋರ್ಟಲ್‌ಗಳ ವಿರುದ್ಧ ತ್ವರಿತ ನೈಜ-ಸಮಯದ ರಕ್ಷಣೆ",
    card1Title: "ಮಹಿಳಾ ಮತ್ತು ಮಕ್ಕಳ ಸುರಕ್ಷತೆ",
    card1Desc: "ಸೈಬರ್ ಕಿರುಕುಳ ಮತ್ತು ಅಪರಾಧಗಳ ಬಗ್ಗೆ ಗೌಪ್ಯ ದೂರು ಸಲ್ಲಿಸಿ.",
    card1Btn: "ದೂರು ಸಲ್ಲಿಸಿ →",
    card2Title: "ಹಣಕಾಸು ವಂಚನೆ ತಡೆಗಟ್ಟುವಿಕೆ",
    card2Desc: "ನಕಲಿ KYC ಮತ್ತು OTP ವಂಚನೆಗಳಿಂದ 24x7 ತಕ್ಷಣದ ರಕ್ಷಣೆ.",
    card3Title: "ಇತರ ಸೈಬರ್ ಅಪರಾಧಗಳು",
    card3Desc: "ರಾನ್ಸಮ್‌ವೇರ್, ಗುರುತು ಕಳ್ಳತನ, ಮಾಲ್‌ವೇರ್ ಮತ್ತು ಇತರ ಸೈಬರ್ ಅಪರಾಧಗಳನ್ನು ವರದಿ ಮಾಡಿ.",
    card3Btn: "ದೂರು ಸಲ್ಲಿಸಿ →",
    dossierBtn: "ವರದಿ ಡೌನ್‌ಲೋಡ್ ಮಾಡಿ",
    helpline1930: "1930 ಗೆ ಕರೆ ಮಾಡಿ",
    a11yTitle: "UX4G ಪ್ರವೇಶಿಸುವಿಕೆ ಆಯ್ಕೆಗಳು",
    colorAdjust: "ಬಣ್ಣ ಮತ್ತು ಕಾಂಟ್ರಾಸ್ಟ್",
    contentAdjust: "ವಿಷಯ ಹೊಂದಾಣಿಕೆ",
    assistiveTools: "ಸಹಾಯಕ ಪರಿಕರಗಳು",
    monochrome: "ಮೊನೊಕ್ರೋಮ್",
    highSaturate: "ಹೆಚ್ಚಿನ ಸ್ಯಾಚುರೇಶನ್",
    lowSaturate: "ಕಡಿಮೆ ಸ್ಯಾಚುರೇಶನ್",
    darkMode: "ಡಾರ್ಕ್ ಮೋಡ್",
    invertColors: "ಬಣ್ಣಗಳನ್ನು ತಿರುಗಿಸಿ",
    biggerText: "ದೊಡ್ಡ ಪಠ್ಯ (A+)",
    lineHeight: "ಸಾಲಿನ ಎತ್ತರ",
    textSpacing: "ಪದಗಳ ಅಂತರ",
    highlightLinks: "ಲಿಂಕ್‌ಗಳನ್ನು ಹೈಲೈಟ್ ಮಾಡಿ",
    dyslexiaFont: "ಡಿಸ್ಲೆಕ್ಸಿಯಾ ಫಾಂಟ್",
    textMagnify: "ಪಠ್ಯ ವರ್ಧಕ",
    screenReader: "ಸ್ಕ್ರೀನ್ ರೀಡರ್",
    voiceSupport: "ಧ್ವನಿ ಬೆಂಬಲ",
    hideImages: "ಚಿತ್ರಗಳನ್ನು ಮರೆಮಾಡಿ",
    focusMode: "ಫೋಕಸ್ ಮೋಡ್",
    pauseAnimation: "ಅನಿಮೇಷನ್ ನಿಲ್ಲಿಸಿ",
    resetAll: "ಮರುಹೊಂದಿಸಿ",
    needHelp: "ಸಹಾಯ ಬೇಕೇ?",
    nationalPortalsHeading: "ರಾಷ್ಟ್ರೀಯ ಪೋರ್ಟಲ್‌ಗಳು",
    emergencyHelplinesHeading: "ತುರ್ತು ಸಹಾಯವಾಣಿ",
    footerAbout: "140 ಕೋಟಿ ಭಾರತೀಯ ನಾಗರಿಕರನ್ನು ನಕಲಿ ಪೋರ್ಟಲ್‌ಗಳಿಂದ ರಕ್ಷಿಸಲು UX4G ವಿನ್ಯಾಸ ವ್ಯವಸ್ಥೆ 3.0 ರ ಅಡಿಯಲ್ಲಿ ಅಭಿವೃದ್ಧಿಪಡಿಸಲಾಗಿದೆ.",
    footerSIH: "UX4G ವಿನ್ಯಾಸ ವ್ಯವಸ್ಥೆ 3.0 • ಸ್ಮಾರ್ಟ್ ಇಂಡಿಯಾ ಹ್ಯಾಕಥಾನ್ 2026",
    closeModal: "ಮುಚ್ಚಿ",
    copyDossier: "ವರದಿ ನಕಲಿಸಿ",
    copied: "ನಕಲಿಸಲಾಗಿದೆ!",
    speechThreat: "ಎಚ್ಚರಿಕೆ! ... ಇದು ಸಂಪೂರ್ಣ ನಕಲಿ ವೆಬ್‌ಸೈಟ್ ಆಗಿದೆ. ... ಆಧಾರ್ ಅಥವಾ ಬ್ಯಾಂಕ್ ವಿವರಗಳನ್ನು ಎಂದಿಗೂ ಹಂಚಿಕೊಳ್ಳಬೇಡಿ. ... ತಕ್ಷಣ 1930 ಸಹಾಯವಾಣಿಗೆ ಕರೆ ಮಾಡಿ.",
    speechSafe: "ಪರಿಶೀಲಿಸಲಾಗಿದೆ! ... ಇದು ಭಾರತ ಸರ್ಕಾರದ ಅಧಿಕೃತ ಪೋರ್ಟಲ್ ಆಗಿದೆ.",
    speechCaution: "ಎಚ್ಚರದಿಂದಿರಿ! ... ಈ ತಾಣ ಸರ್ಕಾರಿ ಪಟ್ಟಿಯಲ್ಲಿ ಇಲ್ಲ."
  },
  ml: {
    govIndia: "ഭാരത സർക്കാർ",
    skipContent: "പ്രധാന ഉള്ളടക്കത്തിലേക്ക് പോകുക",
    brandSubtitle: "ദേശീയ മൾട്ടി-സിഗ്നൽ വ്യാജ പോർട്ടൽ കണ്ടെത്തൽ സംവിധാനം",
    heroTitlePrefix: "ഏതൊരു സർക്കാർ വെബ്‌സൈറ്റും തൽക്ഷണം പരിശോധിക്കുക.",
    heroTitleAi: "ദേശീയ AI സുരക്ഷയോടെ",
    heroSub: "ആധാർ, പാൻ അല്ലെങ്കിൽ ബാങ്ക് വിവരങ്ങൾ നൽകുന്നതിന് മുൻപ്, പോർട്ടൽ യഥാർത്ഥ സർക്കാർ സൈറ്റാണോ അതോ വ്യാജ ക്ലോണാണോ എന്ന് പരിശോധിക്കുക.",
    placeholder: "വെബ്‌സൈറ്റ് ലിങ്ക് ഇവിടെ നൽകുക...",
    verifyBtn: "പരിശോധിക്കുക",
    verifying: "പരിശോധിക്കുന്നു...",
    quickTry: "ടെസ്റ്റ് ലിങ്കുകൾ:",
    safeSite: "സുരക്ഷിതം (PM-Kisan)",
    fakeSite: "വ്യാജ സൈറ്റ് (g0v.in)",
    incomeTax: "ഇൻകം ടാക്സ് പോർട്ടൽ",
    verdictSafe: "യഥാർത്ഥ സർക്കാർ പോർട്ടൽ",
    verdictThreat: "മുന്നറിയിപ്പ്! വ്യാജ വെബ്സൈറ്റ്",
    verdictCaution: "ജാഗ്രത: സംശയാസ്പദമായ ലിങ്ക്",
    listenAudio: "ശബ്ദത്തിൽ കേൾക്കുക",
    stopAudio: "ശബ്ദം നിർത്തുക",
    threatScoreLabel: "അപകട സാധ്യത സ്കോർ (Threat Score)",
    advisorySafe: "ഈ വെബ്‌സൈറ്റ് ഭാരത സർക്കാരിന്റെ അംഗീകൃത പോർട്ടലാണ്. സുരക്ഷിതമായി ഉപയോഗിക്കാം.",
    advisoryThreat: "അപകടം! ഇത് വ്യാജ വെബ്‌സൈറ്റാണ്. ആധാർ, ബാങ്ക് വിവരങ്ങൾ അല്ലെങ്കിൽ OTP ഒരിക്കലും നൽകരുത്!",
    advisoryCaution: "ജാഗ്രത പാലിക്കുക. ഈ ഡൊമെയ്ൻ സർക്കാർ പട്ടികയിൽ ഉൾപ്പെട്ടിട്ടില്ല.",
    layer1: "1. ഔദ്യോഗിക സർക്കാർ ഡൊമെയ്ൻ (.gov.in / .nic.in)",
    layer2: "2. സ്പെല്ലിംഗ് തട്ടിപ്പ് പരിശോധന (Typosquatting)",
    layer3: "3. വിവര ചോർച്ച ഫോം സ്കാനർ",
    layer4: "4. AI വിഷ്വൽ ക്ലോൺ കണ്ടെത്തൽ",
    layer5: "5. ഡൊമെയ്ൻ രജിസ്ട്രേഷനും പഴക്കവും",
    sectionTitle: "പൗര സൈബർ സുരക്ഷാ സേവനങ്ങൾ",
    sectionSub: "വ്യാജ പോർട്ടലുകൾക്കെതിരെ തത്സമയ തൽക്ഷണ സുരക്ഷ",
    card1Title: "സ്ത്രീ-ശിശു സംരക്ഷണം",
    card1Desc: "സൈബർ അതിക്രമങ്ങളെക്കുറിച്ച് രഹസ്യമായി പരാതി നൽകുക.",
    card1Btn: "പരാതി നൽകുക →",
    card2Title: "സാമ്പത്തിക തട്ടിപ്പ് പ്രതിരോധം",
    card2Desc: "വ്യാജ കെവൈസി, ബാങ്ക് തട്ടിപ്പുകൾക്കെതിരെ 24x7 അടിയന്തര സഹായം.",
    card3Title: "മറ്റ് സൈബർ കുറ്റകൃത്യങ്ങൾ",
    card3Desc: "റാൻസംവെയർ, ഐഡന്റിറ്റി മോഷണം, മാൽവെയർ, മറ്റ് സൈബർ കുറ്റകൃത്യങ്ങൾ റിപ്പോർട്ട് ചെയ്യുക.",
    card3Btn: "പരാതി നൽകുക →",
    dossierBtn: "റിപ്പോർട്ട് ഡൗൺലോഡ്",
    helpline1930: "1930 ലേക്ക് വിളിക്കുക",
    a11yTitle: "UX4G പ്രവേശനക്ഷമത ഓപ്ഷനുകൾ",
    colorAdjust: "നിറവും കോൺട്രാസ്റ്റും",
    contentAdjust: "ഉള്ളടക്ക ക്രമീകരണം",
    assistiveTools: "സഹായക ഉപകരണങ്ങൾ",
    monochrome: "മോണോക്രോം",
    highSaturate: "കൂടിയ സാച്ചുറേഷൻ",
    lowSaturate: "കുറഞ്ഞ സാച്ചുറേഷൻ",
    darkMode: "ഡാർക്ക് മോഡ്",
    invertColors: "നിറങ്ങൾ മാറ്റുക",
    biggerText: "വലിയ അക്ഷരങ്ങൾ (A+)",
    lineHeight: "വരിയുടെ അകലം",
    textSpacing: "വാക്കുകളുടെ അകലം",
    highlightLinks: "ലിങ്കുകൾ ഹൈലൈറ്റ് ചെയ്യുക",
    dyslexiaFont: "ഡിസ്‌ലെക്സിയ ഫോണ്ട്",
    textMagnify: "ടെക്സ്റ്റ് മാഗ്നിഫയർ",
    screenReader: "സ്ക്രീൻ റീഡർ",
    voiceSupport: "വോയ്‌സ് സപ്പോർട്ട്",
    hideImages: "ചിത്രങ്ങൾ മറയ്ക്കുക",
    focusMode: "ഫോക്കസ് മോഡ്",
    pauseAnimation: "ആനിമേഷൻ നിർത്തുക",
    resetAll: "റീസെറ്റ് ചെയ്യുക",
    needHelp: "സഹായം വേണോ?",
    nationalPortalsHeading: "ദേശീയ പോർട്ടലുകൾ",
    emergencyHelplinesHeading: "അടിയന്തര ഹെൽപ്പ്‌ലൈൻ",
    footerAbout: "140 കോടി ജനങ്ങൾക്ക് വ്യാജ സൈറ്റുകളിൽ നിന്ന് സുരക്ഷ ഉറപ്പാക്കാൻ UX4G ഡിസൈൻ സിസ്റ്റം 3.0 അടിസ്ഥാനമാക്കി വികസിപ്പിച്ചത്.",
    footerSIH: "UX4G ഡിസൈൻ സിസ്റ്റം 3.0 • സ്മാർട്ട് ഇന്ത്യ ഹാക്കത്തോൺ 2026",
    closeModal: "അടയ്ക്കുക",
    copyDossier: "റിപ്പോർട്ട് പകർത്തുക",
    copied: "പകർത്തി!",
    speechThreat: "ജാഗ്രത! ... ഇതൊരു വ്യാജ വെബ്സൈറ്റാണ്. ... ആധാർ അല്ലെങ്കിൽ ബാങ്ക് വിവരങ്ങൾ ഒരിക്കലും നൽകരുത്. ... ഉടൻ 1930 എന്ന നമ്പറിലേക്ക് വിളിക്കുക.",
    speechSafe: "പരിശോധിച്ചു! ... ഇത് ഭാരത സർക്കാരിന്റെ ഔദ്യോഗിക വെബ്സൈറ്റാണ്.",
    speechCaution: "ജാഗ്രത പാലിക്കുക! ... ഇത് ഔദ്യോഗിക സൈറ്റല്ല."
  },
  pa: {
    govIndia: "ਭਾਰਤ ਸਰਕਾਰ",
    skipContent: "ਮੁੱਖ ਸਮੱਗਰੀ ਤੇ ਜਾਓ",
    brandSubtitle: "ਰਾਸ਼ਟਰੀ ਮਲਟੀ-ਸਿਗਨਲ ਨਕਲੀ ਪੋਰਟਲ ਪਛਾਣ ਪ੍ਰਣਾਲੀ",
    heroTitlePrefix: "ਕਿਸੇ ਵੀ ਸਰਕਾਰੀ ਵੈੱਬਸਾਈਟ ਦੀ ਤੁਰੰਤ ਪੜਤਾਲ ਕਰੋ।",
    heroTitleAi: "ਸੰਪ੍ਰਭੂ AI ਦੁਆਰਾ ਸੁਰੱਖਿਅਤ",
    heroSub: "ਆਧਾਰ, ਪੈਨ ਜਾਂ ਬੈਂਕ ਵੇਰਵੇ ਦਰਜ ਕਰਨ ਤੋਂ ਪਹਿਲਾਂ ਜਾਂਚੋ ਕਿ ਪੋਰਟਲ ਅਸਲ ਸਰਕਾਰੀ ਵੈੱਬਸਾਈਟ ਹੈ ਜਾਂ ਨਕਲੀ ਸਾਈਬਰ ਕਲੋਨ।",
    placeholder: "ਵੈੱਬਸਾਈਟ ਦਾ ਲਿੰਕ ਇੱਥੇ ਦਰਜ ਕਰੋ...",
    verifyBtn: "ਪੜਤਾਲ ਕਰੋ",
    verifying: "ਜਾਂਚ ਜਾਰੀ ਹੈ...",
    quickTry: "ਟੈਸਟ ਲਿੰਕ:",
    safeSite: "ਸੁਰੱਖਿਅਤ (PM-Kisan)",
    fakeSite: "ਨਕਲੀ ਸਾਈਟ (g0v.in)",
    incomeTax: "ਇਨਕਮ ਟੈਕਸ ਪੋਰਟਲ",
    verdictSafe: "ਅਸਲ ਸਰਕਾਰੀ ਪੋਰਟਲ",
    verdictThreat: "ਖਤਰਾ! ਨਕਲੀ ਵੈੱਬਸਾਈਟ",
    verdictCaution: "ਸਾਵਧਾਨੀ: ਸ਼ੱਕੀ ਲਿੰਕ",
    listenAudio: "ਆਵਾਜ਼ ਵਿੱਚ ਸੁਣੋ",
    stopAudio: "ਆਵਾਜ਼ ਬੰਦ ਕਰੋ",
    threatScoreLabel: "ਖਤਰਾ ਸਕੋਰ (Threat Score)",
    advisorySafe: "ਇਹ ਵੈੱਬਸਾਈਟ ਭਾਰਤ ਸਰਕਾਰ ਦਾ ਪ੍ਰਮਾਣਿਤ ਪੋਰਟਲ ਹੈ। ਪੂਰੀ ਤਰ੍ਹਾਂ ਸੁਰੱਖਿਅਤ ਹੈ।",
    advisoryThreat: "ਖਤਰਾ! ਇਹ ਨਕਲੀ ਵੈੱਬਸਾਈਟ ਹੈ। ਆਪਣਾ ਆਧਾਰ, ਬੈਂਕ ਵੇਰਵੇ ਜਾਂ OTP ਕਦੇ ਵੀ ਦਰਜ ਨਾ ਕਰੋ!",
    advisoryCaution: "ਸਾਵਧਾਨ ਰਹੋ। ਇਹ ਡੋਮੇਨ ਸਰਕਾਰੀ ਰਜਿਸਟਰੀ ਵਿੱਚ ਦਰਜ ਨਹੀਂ ਹੈ।",
    layer1: "1. ਅਧਿਕਾਰਤ ਸਰਕਾਰੀ ਡੋਮੇਨ (.gov.in / .nic.in)",
    layer2: "2. ਸਪੈਲਿੰਗ ਧੋਖਾਧੜੀ ਜਾਂਚ (Typosquatting)",
    layer3: "3. ਡਾਟਾ ਚੋਰੀ ਫਾਰਮ ਸਕੈਨਰ",
    layer4: "4. AI ਵਿਜ਼ੂਅਲ ਕਲੋਨ ਪਛਾਣ",
    layer5: "5. ਡੋਮੇਨ ਰਜਿਸਟ੍ਰੇਸ਼ਨ ਅਤੇ ਉਮਰ",
    sectionTitle: "ਨਾਗਰਿਕ ਸਾਈਬਰ ਸੁਰੱਖਿਆ ਸੇਵਾਵਾਂ",
    sectionSub: "ਧੋਖੇਬਾਜ਼ ਪੋਰਟਲਾਂ ਦੇ ਖਿਲਾਫ ਤੁਰੰਤ ਰੀਅਲ-ਟਾਈਮ ਸੁਰੱਖਿਆ",
    card1Title: "ਮਹਿਲਾ ਅਤੇ ਬਾਲ ਸੁਰੱਖਿਆ",
    card1Desc: "ਆਨਲਾਈਨ ਪਰੇਸ਼ਾਨੀ ਅਤੇ ਸਾਈਬਰ ਅਪਰਾਧਾਂ ਦੀ ਗੁਪਤ ਰਿਪੋਰਟ ਦਰਜ ਕਰੋ।",
    card1Btn: "ਰਿਪੋਰਟ ਦਰਜ ਕਰੋ →",
    card2Title: "ਵਿੱਤੀ ਧੋਖਾਧੜੀ ਰੋਕਥਾਮ",
    card2Desc: "ਨਕਲੀ ਕੇਵਾਈਸੀ ਅਤੇ ਓਟੀਪੀ ਫਰਾਡ ਤੋਂ 24x7 ਤੁਰੰਤ ਮਦਦ।",
    card3Title: "ਹੋਰ ਸਾਈਬਰ ਅਪਰਾਧ",
    card3Desc: "ਰੈਨਸਮਵੇਅਰ, ਪਛਾਣ ਚੋਰੀ, ਮਾਲਵੇਅਰ ਅਤੇ ਹੋਰ ਸਾਈਬਰ ਅਪਰਾਧਾਂ ਦੀ ਰਿਪੋਰਟ ਦਰਜ ਕਰੋ।",
    card3Btn: "ਰਿਪੋਰਟ ਦਰਜ ਕਰੋ →",
    dossierBtn: "ਰਿਪੋਰਟ ਡਾਊਨਲੋਡ",
    helpline1930: "1930 ਤੇ ਕਾਲ ਕਰੋ",
    a11yTitle: "UX4G ਪਹੁੰਚਯੋਗਤਾ ਵਿਕਲਪ",
    colorAdjust: "ਰੰਗ ਅਤੇ ਕੰਟ੍ਰਾਸਟ",
    contentAdjust: "ਸਮੱਗਰੀ ਵਿਵਸਥਾ",
    assistiveTools: "ਸਹਾਇਕ ਸਾਧਨ",
    monochrome: "ਮੋਨੋਕ੍ਰੋਮ",
    highSaturate: "ਉੱਚ ਸੰਤ੍ਰਿਪਤਾ",
    lowSaturate: "ਘੱਟ ਸੰਤ੍ਰਿਪਤਾ",
    darkMode: "ਡਾਰਕ ਮੋਡ",
    invertColors: "ਰੰਗ ਉਲਟਾਓ",
    biggerText: "ਵੱਡਾ ਟੈਕਸਟ (A+)",
    lineHeight: "ਲਾਈਨ ਦੀ ਉਚਾਈ",
    textSpacing: "ਸ਼ਬਦਾਂ ਦੀ ਦੂਰੀ",
    highlightLinks: "ਲਿੰਕ ਹਾਈਲਾਈਟ ਕਰੋ",
    dyslexiaFont: "ਡਿਸਲੈਕਸੀਆ ਫੌਂਟ",
    textMagnify: "ਟੈਕਸਟ ਮੈਗਨੀਫਾਇਰ",
    screenReader: "ਸਕ੍ਰੀਨ ਰੀਡਰ",
    voiceSupport: "ਵੌਇਸ ਸਪੋਰਟ",
    hideImages: "ਤਸਵੀਰਾਂ ਛੁਪਾਓ",
    focusMode: "ਫੋਕਸ ਮੋਡ",
    pauseAnimation: "ਐਨੀਮੇਸ਼ਨ ਰੋਕੋ",
    resetAll: "ਰੀਸੈਟ ਕਰੋ",
    needHelp: "ਮਦਦ ਚਾਹੀਦੀ ਹੈ?",
    nationalPortalsHeading: "ਰਾਸ਼ਟਰੀ ਪੋਰਟਲ",
    emergencyHelplinesHeading: "ਐਮਰਜੈਂਸੀ ਹੈਲਪਲਾਈਨ",
    footerAbout: "140 ਕਰੋੜ ਨਾਗਰਿਕਾਂ ਨੂੰ ਨਕਲੀ ਪੋਰਟਲਾਂ ਤੋਂ ਬਚਾਉਣ ਲਈ UX4G ਡਿਜ਼ਾਈਨ ਸਿਸਟਮ 3.0 ਦੇ ਅਧੀਨ ਵਿਕਸਤ।",
    footerSIH: "UX4G ਡਿਜ਼ਾਈਨ ਸਿਸਟਮ 3.0 • ਸਮਾਰਟ ਇੰਡੀਆ ਹੈਕਾਥੌਨ 2026",
    closeModal: "ਬੰਦ ਕਰੋ",
    copyDossier: "ਰਿਪੋਰਟ ਕਾਪੀ ਕਰੋ",
    copied: "ਕਾਪੀ ਹੋ ਗਿਆ!",
    speechThreat: "ਸਾਵਧਾਨ! ... ਇਹ ਪੂਰੀ ਤਰ੍ਹਾਂ ਨਕਲੀ ਵੈੱਬਸਾਈਟ ਹੈ। ... ਆਪਣਾ ਆਧਾਰ ਜਾਂ ਬੈਂਕ ਖਾਤਾ ਕਦੇ ਵੀ ਸਾਂਝਾ ਨਾ ਕਰੋ। ... ਤੁਰੰਤ 1930 ਹੈਲਪਲਾਈਨ ਤੇ ਕਾਲ ਕਰੋ।",
    speechSafe: "ਪ੍ਰਮਾਣਿਤ! ... ਇਹ ਭਾਰਤ ਸਰਕਾਰ ਦਾ ਅਸਲ ਪੋਰਟਲ ਹੈ।",
    speechCaution: "ਸਾਵਧਾਨ ਰਹੋ! ... ਇਹ ਡੋਮੇਨ ਸਰਕਾਰੀ ਸੂਚੀ ਵਿੱਚ ਨਹੀਂ ਹੈ।"
  },
  or: {
    govIndia: "ଭାରତ ସରକାର",
    skipContent: "ମୁଖ୍ୟ ବିଷୟବସ୍ତୁକୁ ଯାଆନ୍ତୁ",
    brandSubtitle: "ଜାତୀୟ ମଲ୍ଟି-ସିଗ୍ନାଲ୍ ନକଲି ପୋର୍ଟାଲ୍ ଚିହ୍ନଟ ବ୍ୟବସ୍ଥା",
    heroTitlePrefix: "ଯେକୌଣସି ସରକାରୀ ୱେବସାଇଟ୍ ତୁରନ୍ତ ଯାଞ୍ଚ କରନ୍ତୁ।",
    heroTitleAi: "ସାର୍ବଭୌମ AI ଦ୍ୱାରା ସୁରକ୍ଷିତ",
    heroSub: "ଆଧାର, ପାନ୍ କିମ୍ବା ବ୍ୟାଙ୍କ ତଥ୍ୟ ଦେବା ପୂର୍ବରୁ ଯାଞ୍ଚ କରନ୍ତୁ ଯେ ୱେବସାଇଟ୍ ଅସଲି ଅଟେ କିମ୍ବା ନକଲି ସାଇବର କ୍ଲୋନ୍।",
    placeholder: "ୱେବସାଇଟ୍ ଲିଙ୍କ୍ ଏଠାରେ ଦିଅନ୍ତୁ...",
    verifyBtn: "ଯାଞ୍ଚ କରନ୍ତୁ",
    verifying: "ବିଶ୍ଳେଷଣ ଚାଲିଛି...",
    quickTry: "ପରୀକ୍ଷଣ ଲିଙ୍କ୍:",
    safeSite: "ସୁରକ୍ଷିତ (PM-Kisan)",
    fakeSite: "ନକଲି ସାଇଟ୍ (g0v.in)",
    incomeTax: "ଆୟକର ପୋର୍ଟାଲ",
    verdictSafe: "ପ୍ରମାଣିତ ସରକାରୀ ପୋର୍ଟାଲ",
    verdictThreat: "ବିପଦ! ନକଲି ୱେବସାଇଟ୍",
    verdictCaution: "ସତର୍କତା: ସନ୍ଦେହଜନକ ଲିଙ୍କ୍",
    listenAudio: "ଭଏସରେ ଶୁଣନ୍ତୁ",
    stopAudio: "ଭଏସ୍ ବନ୍ଦ କରନ୍ତୁ",
    threatScoreLabel: "ବିପଦ ସ୍କୋର (Threat Score)",
    advisorySafe: "ଏହି ୱେବସାଇଟ୍ ଭାରତ ସରକାରଙ୍କ ପ୍ରମାଣିତ ପୋର୍ଟାଲ୍। ସମ୍ପୂର୍ଣ୍ଣ ସୁରକ୍ଷିତ।",
    advisoryThreat: "ବିପଦ! ଏହା ଏକ ନକଲି ୱେବସାଇଟ୍। ଆପଣଙ୍କର ଆଧାର, ବ୍ୟାଙ୍କ ତଥ୍ୟ କିମ୍ବା OTP କେବେ ଦିଅନ୍ତୁ ନାହିଁ!",
    advisoryCaution: "ସତର୍କ ରୁହନ୍ତୁ। ଏହି ଡୋମେନ୍ ସରକାରୀ ତାଲିକାରେ ନାହିଁ।",
    layer1: "1. ସରକାରୀ ଡୋମେନ୍ ପ୍ରମାଣୀକରଣ (.gov.in / .nic.in)",
    layer2: "2. ବନାନ ଠକେଇ ଯାଞ୍ଚ (Typosquatting)",
    layer3: "3. ଡାଟା ଚୋରି ଫର୍ମ ସ୍କାନର୍",
    layer4: "4. AI ଭିଜୁଆଲ୍ କ୍ଲୋନ୍ ଚିହ୍ନଟ",
    layer5: "5. ଡୋମେନ୍ ପଞ୍ଜୀକରଣ ଏବଂ ବୟସ",
    sectionTitle: "ନାଗରିକ ସାଇବର ସୁରକ୍ଷା ସେବା",
    sectionSub: "ପ୍ରତାରଣାମୂଳକ ପୋର୍ଟାଲ ବିରୁଦ୍ଧରେ ତୁରନ୍ତ ରିଅଲ୍-ଟାଇମ୍ ସୁରକ୍ଷା",
    card1Title: "ମହିଳା ଓ ଶିଶୁ ସୁରକ୍ଷା",
    card1Desc: "ସାଇବର ନିର୍ଯାତନା ବିରୁଦ୍ଧରେ ଗୋପନୀୟ ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ।",
    card1Btn: "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ →",
    card2Title: "ଆର୍ଥିକ ଠକେଇ ନିବାରଣ",
    card2Desc: "ନକଲି KYC ଓ OTP ଠକେଇରୁ 24x7 ତୁରନ୍ତ ସହାୟତା।",
    card3Title: "ଅନ୍ୟାନ୍ୟ ସାଇବର ଅପରାଧ",
    card3Desc: "ରାନ୍ସମୱେୟାର, ପରିଚୟ ଚୋରି, ମାଲୱେୟାର ଏବଂ ଅନ୍ୟାନ୍ୟ ସାଇବର ଅପରାଧ ରିପୋର୍ଟ କରନ୍ତୁ।",
    card3Btn: "ଅଭିଯୋଗ ଦାଖଲ କରନ୍ତୁ →",
    dossierBtn: "ରିପୋର୍ଟ ଡାଉନଲୋଡ୍",
    helpline1930: "1930 କୁ କଲ୍ କରନ୍ତୁ",
    a11yTitle: "UX4G ଆକ୍ସେସିବିଲିଟି ବିକଳ୍ପ",
    colorAdjust: "ରଙ୍ଗ ଏବଂ କଣ୍ଟ୍ରାଷ୍ଟ",
    contentAdjust: "ବିଷୟବସ୍ତୁ ସଜାଡ଼ିବା",
    assistiveTools: "ସହାୟକ ଉପକରଣ",
    monochrome: "ମୋନୋକ୍ରୋମ୍",
    highSaturate: "ଉଚ୍ଚ ସନ୍ତୃପ୍ତି",
    lowSaturate: "କମ୍ ସନ୍ତୃପ୍ତି",
    darkMode: "ଡାର୍କ ମୋଡ୍",
    invertColors: "ରଙ୍ଗ ଓଲଟାନ୍ତୁ",
    biggerText: "ବଡ଼ ଅକ୍ଷର (A+)",
    lineHeight: "ଧାଡ଼ି ଉଚ୍ଚତା",
    textSpacing: "ଶବ୍ଦ ବ୍ୟବଧାନ",
    highlightLinks: "ଲିଙ୍କ୍ ହାଇଲାଇଟ୍ କରନ୍ତୁ",
    dyslexiaFont: "ଡିସଲେକ୍ସିଆ ଫଣ୍ଟ",
    textMagnify: "ଟେକ୍ସଟ୍ ମ୍ୟାଗ୍ନିଫାୟାର୍",
    screenReader: "ସ୍କ୍ରିନ୍ ରିଡର୍",
    voiceSupport: "ଭଏସ୍ ସପୋର୍ଟ",
    hideImages: "ଛବି ଲୁଚାନ୍ତୁ",
    focusMode: "ଫୋକସ୍ ମୋଡ୍",
    pauseAnimation: "ଆନିମେସନ୍ ବନ୍ଦ କରନ୍ତୁ",
    resetAll: "ରିସେଟ୍ କରନ୍ତୁ",
    needHelp: "ସାହାଯ୍ୟ ଦରକାର?",
    nationalPortalsHeading: "ଜାତୀୟ ପୋର୍ଟାଲ",
    emergencyHelplinesHeading: "ଜରୁରୀକାଳୀନ ହେଲ୍ପଲାଇନ",
    footerAbout: "140 କୋଟି ନାଗରିକଙ୍କୁ ସାଇବର ଠକେଇରୁ ରକ୍ଷା କରିବା ପାଇଁ UX4G ଡିଜାଇନ୍ ସିଷ୍ଟମ୍ 3.0 ଅଧୀନରେ ବିକଶିତ।",
    footerSIH: "UX4G ଡିଜାଇନ୍ ସିଷ୍ଟମ୍ 3.0 • ସ୍ମାର୍ଟ ଇଣ୍ଡିଆ ହାକାଥନ୍ 2026",
    closeModal: "ବନ୍ଦ କରନ୍ତୁ",
    copyDossier: "ରିପୋର୍ଟ କପି କରନ୍ତୁ",
    copied: "କପି ହୋଇଗଲା!",
    speechThreat: "ସାବଧାନ! ... ଏହା ସମ୍ପୂର୍ଣ୍ଣ ନକଲି ୱେବସାଇଟ୍। ... ଆପଣଙ୍କ ଆଧାର କିମ୍ବା ବ୍ୟାଙ୍କ ତଥ୍ୟ କେବେ ଦିଅନ୍ତୁ ନାହିଁ। ... ତୁରନ୍ତ 1930 ହେଲ୍ପଲାଇନକୁ କଲ୍ କରନ୍ତୁ।",
    speechSafe: "ପ୍ରମାଣିତ! ... ଏହା ଭାରତ ସରକାରଙ୍କ ଅସଲ ପୋର୍ଟାଲ୍।",
    speechCaution: "ସତର୍କ ରୁହନ୍ତୁ! ... ଏହି ସାଇଟ୍ ସରକାରୀ ତାଲିକାରେ ନାହିଁ।"
  },
  as: {
    govIndia: "ভাৰত চৰকাৰ",
    skipContent: "মূল বিষয়বস্তুলৈ যাওক",
    brandSubtitle: "ৰাষ্ট্ৰীয় মাল্টি-চিগনেল ভুৱা প'ৰ্টেল চিনাক্তকৰণ ব্যৱস্থা",
    heroTitlePrefix: "যিকোনো চৰকাৰী ৱেবছাইট তৎক্ষণাত পৰীক্ষা কৰক।",
    heroTitleAi: "সাৰ্বভৌম AI দ্বাৰা সুৰক্ষিত",
    heroSub: "আধাৰ, পেন বা বেংক তথ্য দিয়াৰ আগতে পৰীক্ষা কৰক যে প'ৰ্টেলটো প্ৰকৃত চৰকাৰী ৱেবছাইট নে ভুৱা চাইবাৰ ক্ল'ন।",
    placeholder: "ৱেবছাইট লিংক ইয়াত দিয়ক...",
    verifyBtn: "পৰীক্ষা কৰক",
    verifying: "বিশ্লেষণ চলি আছে...",
    quickTry: "পৰীক্ষামূলক লিংক:",
    safeSite: "নিৰাপদ (PM-Kisan)",
    fakeSite: "ভুৱা ছাইট (g0v.in)",
    incomeTax: "আয়কৰ প'ৰ্টেল",
    verdictSafe: "প্ৰমাণিত চৰকাৰী প'ৰ্টেল",
    verdictThreat: "বিপদ! ভুৱা ৱেবছাইট",
    verdictCaution: "সাৱধানবাণী: সন্দেহজনক লিংক",
    listenAudio: "কণ্ঠত শুনক",
    stopAudio: "কণ্ঠ বন্ধ কৰক",
    threatScoreLabel: "বিপদৰ মাত্ৰা (Threat Score)",
    advisorySafe: "এই ৱেবছাইটটো ভাৰত চৰকাৰৰ প্ৰকৃত প'ৰ্টেল। সম্পূৰ্ণ নিৰাপদ।",
    advisoryThreat: "বিপদ! এইটো ভুৱা ৱেবছাইট। কেতিয়াও আপোনাৰ আধাৰ, বেংক তথ্য বা OTP নিদিব!",
    advisoryCaution: "সাৱধান হওক। এই ডমেইনটো চৰকাৰী তালিকাত নাই।",
    layer1: "১. চৰকাৰী ডমেইন প্ৰমাণীকৰণ (.gov.in / .nic.in)",
    layer2: "২. বানান প্ৰতাৰণা পৰীক্ষা (Typosquatting)",
    layer3: "৩. তথ্য চুৰি ফৰ্ম স্কেনাৰ",
    layer4: "৪. AI দৃশ্যমান ক্ল'ন চিনাক্তকৰণ",
    layer5: "৫. ডমেইন পঞ্জীয়ন আৰু বয়স",
    sectionTitle: "নাগৰিক চাইবাৰ সুৰক্ষা সেৱা",
    sectionSub: "প্ৰতাৰণামূলক প'ৰ্টেলৰ বিৰুদ্ধে তাৎক্ষণিক সুৰক্ষা",
    card1Title: "মহিলা আৰু শিশু সুৰক্ষা",
    card1Desc: "অনলাইন হাৰাশাস্তিৰ বিৰুদ্ধে গোপনীয় অভিযোগ দাখিল কৰক।",
    card1Btn: "অভিযোগ দাখিল কৰক →",
    card2Title: "আৰ্থিক প্ৰতাৰণা প্ৰতিৰোধ",
    card2Desc: "ভুৱਾ কেৱাইচি আৰু অ'টিপি জালিয়াতিৰ পৰা ২৪x৭ সহায়।",
    card3Title: "অন্যান্য চাইবাৰ অপৰাধ",
    card3Desc: "ৰেঞ্চমৱেৰ, পৰিচয় চুৰি, মেলৱেৰ আৰু অন্যান্য চাইবাৰ অপৰাধৰ অভিযোগ দাখিল কৰক।",
    card3Btn: "অভিযোগ দাখিল কৰক →",
    dossierBtn: "প্ৰতিবেদন ডাউনলোড",
    helpline1930: "১৯৩০ নম্বৰত কল কৰক",
    a11yTitle: "UX4G প্ৰৱেশাধিকাৰ বিকল্প",
    colorAdjust: "ৰং আৰু বৈসাদৃশ্য",
    contentAdjust: "বিষয়বস্তু সমন্বয়",
    assistiveTools: "সহায়ক সঁজুলি",
    monochrome: "মনোক্ৰ'ম",
    highSaturate: "উচ্চ সংপৃক্ততা",
    lowSaturate: "কম সংপৃক্ততা",
    darkMode: "ডাৰ্ক ম'ড",
    invertColors: "ৰং ওলোটাওক",
    biggerText: "ডাঙৰ আখৰ (A+)",
    lineHeight: "শাৰীৰ উচ্চতা",
    textSpacing: "শব্দৰ ব্যৱধান",
    highlightLinks: "লিংক উজ্জ্বল কৰক",
    dyslexiaFont: "ডিছলেক্সিয়া ফন্ট",
    textMagnify: "টেক্সট মেগ্নিফায়াৰ",
    screenReader: "স্ক্ৰীণ ৰিডাৰ",
    voiceSupport: "ভইচ চাপৰ্ট",
    hideImages: "ছবি লুকুৱাওক",
    focusMode: "ফ'কাচ ম'ড",
    pauseAnimation: "এনিমেচন বন্ধ কৰক",
    resetAll: "পুনৰ সংহতি কৰক",
    needHelp: "সহায় লাগিব নেকি?",
    nationalPortalsHeading: "ৰাষ্ট্ৰীয় প'ৰ্টেল",
    emergencyHelplinesHeading: "জৰুৰীকালীন হেল্পলাইন",
    footerAbout: "১৪০ কোটি নাগৰিকক চাইবাৰ প্ৰতাৰণাৰ পৰা ৰক্ষা কৰিবলৈ UX4G ডিজাইন ব্যৱস্থা ৩.০ ৰ অধীনত বিকশিত।",
    footerSIH: "UX4G ডিজাইন ব্যৱস্থা ৩.০ • স্মাৰ্ট ইণ্ডিয়া হেকাথন ২০২৬",
    closeModal: "বন্ধ কৰক",
    copyDossier: "প্ৰতিবেদন কপি কৰক",
    copied: "কপি হ'ল!",
    speechThreat: "সাৱধান! ... এইটো এটা সম্পূৰ্ণ ভুৱা ৱেবছাইট। ... আপোনাৰ আধাৰ বা বেংক তথ্য কেতিয়াও নিদিব। ... ততালিকে ১৯৩০ নম্বৰত কল কৰਕ।",
    speechSafe: "প্ৰমাণিত! ... এইটো ভাৰত চৰকাৰৰ প্ৰকৃত প'ৰ্টেল।",
    speechCaution: "সাৱধান হওক! ... এই ছাইটটো চৰকাৰী তালিকাত নাই।"
  }
};
